### ISSUE TITLE
APIキーをsecretから読み取るようにする

### ISSUE THREAD

**Issue by kokoichi206** [android-project-46group/android#63]
github actions で secret key を扱う練習と思ってやってみる

### 目標
- secret key から情報が取得できること
- artifacts の apk でも、きちんと API の結果が取得できる（画面が真っ白にならない）こと

**Comment by kokoichi206** [comment]
### Links
- [Encrypted secrets](https://docs.github.com/ja/actions/security-guides/encrypted-secrets)
- [登録できる箇所とスコープ](https://qiita.com/inouet/items/c7d39ac4641c05eec4a0)
- [Environment を登録しろおおおお](https://stackoverflow.com/questions/66521958/how-to-access-environment-secrets-from-a-github-workflow)
  - [公式](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#referencing-an-environment)

**Comment by kokoichi206** [comment]
### Steps
1. API_KEY の部分を環境変数から読み取るように変更する
2. Actions の中でどのように環境変数を読み解くのかなどを調べる

**Comment by kokoichi206** [comment]
> Android Studioは環境変数をGradleに渡さないため、実行しようとしていることはIDEからは機能しません。ビルドファイルにキーストアパスワードを保持しないようにする方法が必要な場合は、別のファイルにパスワードを保存するためのコードを含む回答を次に示します。

**Comment by kokoichi206** [comment]
release ビルドで試しにやってみたら、次のようなエラーが出たため、リリースビルド対応は別チケットで行う

```
Performing Streamed Install
adb: failed to install app-release-unsigned.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: 
Failed collecting certificates for /data/app/vmdl1191472956.tmp/base.apk: Failed to collect 
certificates from /data/app/vmdl1191472956.tmp/base.apk: Attempt to get length of null array]
```

build command

`./gradlew assembleRelease`

apk path

`path: app/build/outputs/apk/release/app-release-unsigned.apk`

**Comment by kokoichi206** [comment]
Environment の登録を忘れていて3時間溶かしました、ありがとうございました

登録しないと、secrets が永遠に読めませんでした

今回は以下のように、各 job 配下に設置しましたが、全体に適応させるのもありかもしれません

``` yml
jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    # You have to specify the environment to use secrets.
    environment: production
    steps:
      - name: Check out
        uses: actions/checkout@v2
```
